Repositorio/fundacion/apps/eventos/urls.py
from django.urls import path 
from . import views

app_name = 'eventos'

urlpatterns = [

path('', views.eventos, name = 'eventos_listar'),

] 

Repositorio/fundacion/apps/noticias/urls.py
from django.urls import path

from . import views

app_name = 'noticias'

urlpatterns = [
    
    path('listar/', views.Listar, name = 'listar_noticias'),

    path('detalle/<int:pk>', views.Detalle_Noticia.as_view(), name = 'detalle_noticias'),

    path('add_comentario/<int:pk>', views.Agregar_Comentario, name='agregar_comentario'),

    ]

Repositorio/fundacion/apps/somos/urls.py
from django.urls import path
from . import views 


app_name = "somos"
urlpatterns = [
    
    path('quienes/', views.Quienes, name = 'quienes_somos'),
]

Repositorio/fundacion/apps/usuarios/urls.py
from django.urls import path 

from . import views

app_name = "registrarse"

urlpatterns = [

    path('registrar/', views.registrar.as_view(), name="registrar"),

]

Repositorio/fundacion/fundacion/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include    
from . import views 
from django.conf import settings
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.Home, name = 'home'),

    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"), 
    path('Somos/', include('apps.somos.urls')),
    path('Noticias/', include('apps.noticias.urls')),
    path('Eventos/', include('apps.eventos.urls')),
    path('Registrarse/', include('apps.usuarios.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Repositorio/fundacion/apps/eventos/models.py
from django.db import models


class Eventos(models.Model):
	titulo = models.CharField(max_length = 120)
	fecha = models.DateField(auto_now_add = True)
	detalle = models.TextField()
	imagen = models.ImageField(upload_to = 'eventos', null=True, blank = True)

	def __str__(self):
		return self.titulo

Repositorio/fundacion/apps/noticias/models.py
from django.db import models

from apps.usuarios.models import Usuario

# Create your models here.
class Categoria(models.Model):
	nombre = models.CharField(max_length = 60)
	descripcion = models.CharField(max_length = 250, null = True, blank = True)

	def __str__(self):
		return self.nombre


class Noticia(models.Model):
	titulo = models.CharField(max_length = 120)
	creado = models.DateField(auto_now_add = True)
	cuerpo = models.TextField()
	autor = models.CharField(max_length = 50, null=True, blank = True)
	imagen = models.ImageField(upload_to = 'noticias', null=True, blank = True)
	categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE,null = True, blank = True)

	def __str__(self):
		return self.titulo

	def obtener_mis_comentarios(self):
		return self.mis_comentarios.all() 


class Comentario(models.Model):
	noticia = models.ForeignKey(Noticia, related_name= 'mis_comentarios', on_delete= models.CASCADE)
	texto= models.TextField()
	creado= models.DateTimeField(auto_now_add = True)
	usuario= models.ForeignKey(Usuario, related_name= 'usuario_comentario', on_delete= models.CASCADE)

	def __str__(self):
		return self.texto

Repositorio/fundacion/apps/somos/models.py
from django.db import models
class Somos(models.Model):
	titulo = models.CharField(max_length = 120)
	creado = models.DateField(auto_now_add = True)
	cuerpo = models.TextField()
	autor = models.CharField(max_length = 50, null=True, blank = True)
	imagen = models.ImageField(upload_to = 'somos', null=True, blank = True)


	def __str__(self):
		return self.titulo

Repositorio/fundacion/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser 

class Usuario(AbstractUser):
	pass

Repositorio/fundacion/apps/usuarios/forms.py
import email
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class registrarForm(UserCreationForm):

    class Meta:

        model = Usuario
        fields = ["first_name", "last_name", "email", "username", "password1", "password2"]

Repositorio/fundacion/apps/eventos/views.py
from django.shortcuts import render
from .models import Eventos

def eventos(request):
	ctx = {}
	todos = Eventos.objects.all() 
	print(todos)

	ctx['evento'] = todos

	return render(request,'eventos/eventos_listar.html',ctx)

Repositorio/fundacion/apps/noticias/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from .models import Noticia, Comentario


def Listar(request):
	busqueda = request.GET.get("buscar",None)
	print(busqueda)
	if busqueda:
		noticias = Noticia.objects.filter(titulo__icontains = busqueda)
	else:
		noticias = Noticia.objects.all()
	print(noticias)
	return render(request, 'noticias/listar_noticias.html', {'notis':noticias})

	return render(request,'noticias/listar_noticias.html',ctx)

class Detalle_Noticia(LoginRequiredMixin, DetailView):
	model = Noticia
	template_name = 'noticias/detalle_noticia.html'

def Agregar_Comentario(request,pk):
	texto_comentario = request.POST.get('comment')
	
	noti = Noticia.objects.get(pk = pk)

	c = Comentario.objects.create(noticia = noti, texto = texto_comentario, usuario = request.user)

	return HttpResponseRedirect(reverse_lazy('noticias:detalle_noticias', kwargs={'pk':pk}))

Repositorio/fundacion/apps/somos/views.py
from django.shortcuts import render


from .models import Somos

def Quienes(request):
	ctx = {}	
	
	todas = Somos.objects.all()
	
	ctx['notis'] = todas

	return render(request,'quienes_somos.html',ctx)

Repositorio/fundacion/apps/usuarios/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView

from .models import Usuario
from .forms import registrarForm

class registrar(CreateView):
    model = Usuario
    template_name = "usuarios/registrar.html"
    form_class = registrarForm 

    def get_success_url(self, **kwargs):
        return reverse('home')

Repositorio/fundacion/fundacion/views.py
from django.shortcuts import render

def Home (request):
    return render(request,'home.html')

Repositorio/fundacion/templates/base.html
{% load static %}
<!doctype html>
<html lang="es-ar">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fundación C.E.B.s</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"> 
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </head>
  <body style="background-color:aliceblue ;">
    <!--Inicio de barra de navegación-->
    <nav class="navbar navbar-expand-lg"style="background-color:#74b9ff;z-index: 300;">
        <img src="{%static 'img/Logo_fundacion1png.png' %}" style="width: 50px;  border-radius: 50%;" alt="Logo">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <a class="navbar-brand" href="{% url 'noticias:listar_noticias' %}">Noticias</a>
              <a class="navbar-brand" href="{% url 'somos:quienes_somos' %}">Quienes somos</a>
              <a class="navbar-brand"></a>
                <a class="navbar-brand"  href="https://www.facebook.com/groups/498186250237283/">Facebook</a>
              <a class="navbar-brand" id="margen"></a>
              {% if user.is_authenticated %}
              <span class="navbar-brand" style="color:rgb(113, 113, 237);">Hola!{{user.username}}</span>
              <a class="navbar-brand" href="{%url 'logout' %}"id=>Finalizar Sesion</a>
              {%else%}
                <a class="navbar-brand" href="{%url 'login' %}"id=>Iniciar Sesion</a>
                <a class="navbar-brand" href="{%url 'registrarse:registrar' %}">Registrarse</a>
              {% endif %}           
            </ul>
          </div>
        </div>
      </nav>
     <br>
   
      {%block contenido%}

      {%endblock contenido%}
     
      <br>
     
        <!-- Footer -->
        <footer id="footer" class="bg-secondary text-white text-center text-md-start">
          <!-- Grid container -->
          <div class="container p-4">
            <!--Grid row-->
            <div class="row">
              <!--Grid column-->
              <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                <h5 class="text-uppercase">Nuesta Misión</h5>
                <p>
                  “Lo que hemos oído, lo que hemos visto con nuestros ojos. Lo que hemos mirado y nuestras manos han palpado acerca del Verbo que es Vida…lo que hemos visto y oído se lo damos a conocer” (1 Jn 1,1.3a)
                </p>
              </div>
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase mb-0">Enlaces:</h5>
      
                <ul class="list-unstyled">
                  <li>
                    <a href="https://goo.gl/maps/ZFDwDubkYtScd9SY8">
                    <img src="{%static 'img/google_maps.png'%}"style="width: 50px;  border-radius: 50%;" alt="">
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'eventos:eventos_listar'%}" class="text-white" >Eventos</a>
                  </li>
                  <li>
                    <h6>Correo: electrónico:castellicebs19@gmail.com</h6>
                  </li>
                 
                </ul>
              </div>
              <!--Grid column-->
            </div>
            <!--Grid row-->
          </div>
          <!-- Grid container -->
      
          <!-- Copyright -->
          <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2022 Copyright:
            <h6>Informatorio 2022 Grupo 2</h6>
          </div>
          <!-- Copyright -->
        </footer>
        <!-- Footer -->

</html>

Repositorio/fundacion/templates/eventos/eventos_listar.html
{%extends 'base.html'%}
{% load static %}

{% block contenido %}
 <link rel="stylesheet" href="{%static 'css/calendario.css'%}">
<h1 style= "text-align:center; font-family: Arial;" >EVENTOS</h1>

 {% for n in evento%}
        <br>
        <h5 style="padding-left: 12px;">{{n.titulo}}<h5>
        <h5 style="padding-left: 12px;">{{n.detalle}}</h5>
        <h5 style="padding-left: 12px;">{{n.fecha}}</h5>
        <img style="padding-left: 12px;">{{n.imagen}}</img>
        <br>

    {% endfor %}
       
    <div>
      <h6>Septiembre 2022</h6>
      
      <ol>
      <li class="day_name">Lun</li>
      <li class="day_name">Mar</li>
      <li class="day_name">Mie</li>
      <li class="day_name">Jue</li>
      <li class="day_name">Vie</li>
      <li class="day_name">Sab</li>
      <li class="day_name">Dom</li>
      <l1 class="primero">1</l1>
      <l1>2</l1>
      <l1>3</l1>
      <l1>4</l1>
      <l1>5</l1>
      <l1>6</l1>
      <l1>7</l1>
      <l1>8</l1>
      <l1>9</l1>
      <l1>10</l1>
      <l1>11</l1>
      <l1>12</l1>
      <l1>13</l1>
      <l1>14</l1>
      <l1>15</l1>
      <l1>16</l1>
      <l1>17</l1>
      <l1>18</l1>
      <l1>19</l1>
      <l1>20</l1>
      <l1>21</l1>
      <l1>22</l1>
      <l1>23</l1>
      <l1>24</l1>
      <l1>25</l1>
      <l1>26</l1>
      <l1>27</l1>
      <l1>28</l1>
      <l1>29</l1>
      <l1>30</l1>
      <l1>31</l1>
    </ol>
  </div>
 
{% endblock contenido %}

Repositorio/fundacion/templates/home.html
{%extends 'base.html'%}
{% load static %}
      {%block contenido%}
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active text-center">
            <img src="{%static 'img/Fundación11.jpg'%}"style="width: 40%";class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item active text-center">
            <img src="../static/img/Fundación_212.jpg"style="width: 40%";class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item active text-center">
            <img src="../static/img/Fundacion77_n.jpg"style="width: 40%";class="d-block w-100" alt="...">
          </div>
        </div>
      </div> 
  
{%endblock contenido%}
   

Repositorio/fundacion/templates/noticias/detalle_noticia.html
{%extends 'base.html'%}
{% load static %}

{%block contenido%}
<!--	<h1>Noticias</h1>
		<br>
		<h2>Noticia numero:{{codigo}}</h2>	--->
			
    	<h2 style="text-align:center; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"   >{{object.titulo}}</h2>
    	
    	{% if object.autor %}
        	<p style="padding-left: 10px;">AUTOR: {{ object.autor }}</p>
    	{% endif %}
    	<p style="padding-left: 10px;" >CUERPO: {{ object.cuerpo }}</p>


    	{% if object.imagen %}
        	<img src="{{ object.imagen.url }}"style="padding-left: 10px;" width="500px" height="500px">
    	{% else %}
        	<p style="padding-left: 10px;" >NO TIENE IMAGEN </p>
    	{% endif %}
		<p style="padding-left: 10px;"> CATEGORIA:{{ object.categoria.nombre }}</p> 

    <h4 style="padding-left: 10px; font-family: Arial;">Comentarios:</h4><br>
    	{% for x in object.obtener_mis_comentarios %}
        	<b style="padding-left: 10px;">{{x.usuario}}</b>
        	<p style="padding-left: 10px;">{{x.creado}}</p>
        	<p style="padding-left: 10px;">{{x.texto}}</p>  
    	{% endfor %}
    

    	{% if user.is_authenticated %}
        	<form method="POST" action= "{% url 'noticias:agregar_comentario' object.pk %}" style="padding-left: 10px;">{% csrf_token %}
            	<textarea rows="5" cols="50" name="comment" placeholder="Comentar"></textarea>     
            	<button class="btn btn-primary"  type="submit" style="padding-left: 10px; background-color:cornflowerblue; vertical-align:50%;">COMENTAR</button>
		
        	</form>
    
    	{% endif %}



{%endblock contenido%}

Repositorio/fundacion/templates/noticias/listar_noticias.html
{%extends 'base.html'%}
{% load static %}

{%block contenido%}
    <h3 style="padding-left: 12px;">Noticias: </h3>
    
    {% for n in notis%}
        <br>
        <h5 style="padding-left: 12px;">{{n.titulo}}<h5>
        
        <a style="padding-left: 12px;" href="{% url 'noticias:detalle_noticias' n.pk %}">Mas Detalles</a>
        <br>

    {% endfor %}
    <br>
<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"method="GET">

    <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Buscar..." name="buscar" value="{{ request.GET.buscar }}">
            <div class="input-group-append">
            <button class="btn btn-primary" type="submit">Buscar
                <i class="fas fa-search fa-sm"></i>
            </button>
        </div>
    </div>
</form>
<br>
  
{%endblock contenido%}

    

Repositorio/fundacion/templates/quienes_somos.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
	<br>
	<center><h1>¿Quienes somos?</h1></center>
	<br>
	<p style="text-align: center;">
		La CEBs por estar insertada en los barrios más humildes de la ciudad y en la zona rural, son una instancia misionera de la iglesia más próxima a las personas y hacen más visible la unión entre fe y vida.
		Las CEBs articulan el compromiso cristiano “opción por los pobres”, la lucha por la Justicia Social, los Derechos Humanos, de Género y de nuestros Pueblos Originarios, llevando adelante obras caritativas y solidarias.
	</p>
	<center><img src="{% static 'img/datos_1.jpg' %}"style="width: 600px";></center>
	<p style="text-align: left;padding-left: 5px;">
<br>		
Entre las actividades que realizan, se encuentran: <br>

⦁	Talleres de Derechos humanos <br>
⦁	Talleres sobre Violencia de Género <br> 
⦁	Talleres sobre Adicciones <br>
⦁	Talleres de Emprendimiento <br>
⦁	Huerta Orgánica <br>
⦁	Organizar Fiestas Patronales <br> 
⦁	Charlas sobre inquietudes y problemas de zonas desfavorables para luego llevarlas con la autoridad correspondiente <br>
⦁	Encuentros con los Jóvenes
	</p>
{% endblock contenido %}

Repositorio/fundacion/templates/usuarios/login.html
{% load static %}
    {%block contenido%}
	<main role="main">
		
	<div class="container">
    <div class="login-box" > 
		<link rel="stylesheet" href="../../static/css/login.css">
		<img class="avatar" src="{% static 'img/Logo_fundacion1png.png' %}" alt="Logo de Fundación">
		<h1>Iniciar Sesion</h1>
		<form method="POST">{%csrf_token%}
			{{form.errors}}
			<input type="text" name="username" placeholder="USUARIO">
			<input type="password" name="password" placeholder="PASSWORD">
			<input type="submit" name="" value="ENVIAR">
		</form>
	</div>	
	</div>
	</main>
    {%endblock contenido%}

Repositorio/fundacion/templates/usuarios/registrar.html
{% extends 'base.html' %}

{% block contenido %}
    
    <body style="background-color: black;">
        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row" style="margin-left : 20%;margin-right: 20%; margin-top: 5%;border: 2px solid black; background-color:#74b9ff; ">
                    <div class="col">
                        <form method="post">{% csrf_token %}
                            <div class="h1" style="margin-left: 23%;">REGISTRAR USUARIO</div>

                                {{form.as_p}}
                                <br>
                                <button type="submit" class="btn btn-primary" style="margin-left: 40%;">Registar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
      <br><br><br><br>
    </body>

{% endblock contenido %}